#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-basic
  annotations:
    tekton.dev/git-0: #@ data.values.imported.git.host 
type: kubernetes.io/basic-auth
stringData:
  username: AnthonyQi2022
  password: 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
